prooph_service_bus:
  command_buses:
    product_command_bus:
      router:
        type: 'prooph_service_bus.command_bus_router'
    basket_command_bus:
      router:
        type: 'prooph_service_bus.command_bus_router'
        
  event_buses:
    product_event_bus:
      plugins:
        - 'prooph_service_bus.on_event_invoke_strategy'
      router:
        type: 'prooph_service_bus.event_bus_router'

    basket_event_bus:
      plugins:
        - 'prooph_service_bus.on_event_invoke_strategy'
      router:
        type: 'prooph_service_bus.event_bus_router'
