prooph_event_store:
    stores:
        product_store:
            event_store: Prooph\EventStore\Pdo\MariaDbEventStore
            repositories:
                product_collection:
                    repository_class: Infrastructure\Product\EventStoreProductRepository
                    aggregate_type: Domain\Product\Product
                    aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\EventStoreAggregateTranslator
                basket_collection:
                    repository_class: Infrastructure\Basket\EventStoreBasketRepository
                    aggregate_type: Domain\Basket\Basket
                    aggregate_translator: Prooph\EventSourcing\EventStoreIntegration\EventStoreAggregateTranslator

    projection_managers:
        product_projection_manager:
            event_store: Prooph\EventStore\Pdo\MariaDbEventStore
            connection: Doctrine\DBAL\Driver\Connection
            projections:
                product_projection:
                    read_model: Infrastructure\Product\Projection\ProductReadModel
                    projection: Infrastructure\Product\Projection\ProductProjection

        basket_projection_manager:
            event_store: Prooph\EventStore\Pdo\MariaDbEventStore
            connection: Doctrine\DBAL\Driver\Connection
            projections:
                basket_projection:
                    read_model: Infrastructure\Basket\Projection\BasketReadModel
                    projection: Infrastructure\Basket\Projection\BasketProjection
