version: '2'

services:
    db:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - .env
        volumes:
            - ./var/maria:/var/lib/mysql

    mongodb:
        image: mongo
        ports:
            - "27017:27017"
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
            - "25672:25672"
        env_file:
            - .env
    php:
        build: ./config/docker/php-fpm
        expose:
            - "9000"
        env_file:
              - .env
        volumes:
            - ./bin:/var/www/html/bin
            - ./config:/var/www/html/config
            - ./src:/var/www/html/src
            - ./resources:/var/www/html/resources
            - ./public:/var/www/html/public
            - ./var/import:/var/www/html/var/import
            - ./composer.json:/var/www/html/composer.json
            - ./composer.lock:/var/www/html/composer.lock
            - ./symfony.lock:/var/www/html/symfony.lock
            - ./Makefile:/var/www/html/Makefile
            - ./.env:/var/www/html/.env
            - ./.cache/composer:/root/.composer
        links:
            - rabbitmq
            - mongodb
    nginx:
        build: ./config/docker//nginx
        ports:
            - "80:8181"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./var/log/:/var/log/nginx
    elk:
        build: ./config/docker/elk
        ports:
            - "5601:5601"
            - "9201:9200"
            - "5044:5044"
            - "12201:12201"
