version: '2'

services:
    db:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - .env
        volumes:
            - ./var/maria:/var/lib/mysql
            - ./vendor/prooph/pdo-event-store/scripts/mariadb:/docker-entrypoint-initdb.d

    php:
        build: ./config/docker/php-fpm
        expose:
            - "9000"
        env_file:
              - .env
        volumes:
            - ./var/
            - ./vendor/
            - ./bin:/var/www/html/bin
            - ./config:/var/www/html/config
            - ./src:/var/www/html/src
            - ./resources:/var/www/html/resources
            - ./public:/var/www/html/public
            - ./var/import:/var/www/html/var/import
            - ./composer.json:/var/www/html/composer.json
            - ./composer.lock:/var/www/html/composer.lock
            - ./symfony.lock:/var/www/html/symfony.lock
            - ./Makefile:/var/www/html/Makefile
            - ./.env:/var/www/html/.env
            - ./.cache/composer:/root/.composer

    nginx:
        build: ./config/docker/nginx
        ports:
            - "80:8181"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./var/log/:/var/log/nginx

    projection_product:
        image: prooph/php:7.2-cli
        entrypoint: /app/bin/wait_for_sql.sh
        volumes:
          - ./:/app
        depends_on:
          - db
        command: php bin/console event-store:projection:run product_projection

    projection_basket:
        image: prooph/php:7.2-cli
        entrypoint: /app/bin/wait_for_sql.sh
        volumes:
          - ./:/app
        depends_on:
          - db
        command: php bin/console event-store:projection:run basket_projection