parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Application\:
        resource: '../src/Application/*'
        exclude: '../src/Application/{Action,Migrations,Tests,Kernel.php}'

    Application\Action\:
        resource: '../src/Application/Action'
        tags: ['controller.service_arguments']

    Application\Listener\JsonRequestTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1000 }

    Application\Action\Product\CreateNewProductAction:
        arguments: ['@prooph_service_bus.product_command_bus']
        tags: ['controller.service_arguments']

    Application\Action\Basket\AddProductToBasketAction:
          arguments: ['@prooph_service_bus.basket_command_bus']
          tags: ['controller.service_arguments']

    Application\Action\Basket\GetBasketAction:
              arguments: ['@prooph_service_bus.basket_command_bus']
              tags: ['controller.service_arguments']

    Doctrine\DBAL\Driver\Connection:
        class: Doctrine\DBAL\Driver\PDOConnection
        factory: ['@database_connection', getWrappedConnection]