services:
    Domain\Product\Handler\CreateNewProductHandler:
        arguments: ['@product_collection']
        public: true
        tags:
            - { name: 'prooph_service_bus.product_command_bus.route_target', message_detection: true }

    Domain\Basket\Handler\CreateNewBasketHandler:
        arguments: ['@basket_collection']
        public: true
        tags:
            - { name: 'prooph_service_bus.basket_command_bus.route_target', message_detection: true }

    Domain\Basket\Handler\AddProductToBasketHandler:
        arguments: ['@basket_collection', '@product_collection']
        public: true
        tags:
            - { name: 'prooph_service_bus.basket_command_bus.route_target', message_detection: true }
