services:
    Domain\Product\Handler\CreateNewProductHandler:
        arguments: ['@product_collection']
        public: true
        tags:
            - { name: 'prooph_service_bus.product_command_bus.route_target', message_detection: true }
