services:
    # Product
    Infrastructure\Product\EventStoreProductRepository: ~

    Infrastructure\Product\Projection\ProductProjection: ~

    Infrastructure\Product\Projection\ProductFinder:
        arguments: ['@Doctrine\DBAL\Driver\Connection']

    Infrastructure\Product\Projection\ProductReadModel:
        arguments: ['@doctrine.dbal.default_connection']

    # Basket
    Infrastructure\Basket\EventStoreBasketRepository: ~

    Infrastructure\Basket\Projection\BasketProjection: ~

    Infrastructure\Basket\Projection\BasketFinder:
        arguments: ['@Doctrine\DBAL\Driver\Connection']

    Infrastructure\Basket\Projection\BasketReadModel:
        arguments: ['@doctrine.dbal.default_connection']
